name: 'jaffle_shop'
version: '0.1'
config-version: 2
require-dbt-version: ">=0.19.0"
profile: 'snowflake-db'
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

models:
  jaffle_shop:
      +database: DEV
      materialized: table
      staging:
        materialized: view
        tags: ["staging", "hourly"]